### PR TITLE
restructuring for jupyter, new ipywidgets, installation flexibility

### PR DESCRIPTION
**Pull request by nrbgt**
Hi, love the work!

In trying to get CesiumWidget working for my use case, I've made the following changes:
- use a tuple instance for czml
- adding an installer (to avoid path stuff)
- restructure static files to be a little more sane
  - npm might be good, to reduce churn in the main repo
    - sometimes, i'll still include the static/built files, but as a submodule
- removed jupyter-pip... it's slowly being deprecated
- update some ipywidgets API calls

I'd happily pare down the list if you want smaller chunks!

### CODE REVIEW

**Comment by petrushy** [comment]
Hi! Many thanks for providing inputs to the project!

I'm not too experienced in this, so I have some questions :)

You are suggestion to use a tuple for the czml, what is the reason for this, the czml language is text, there probably is a reason I dont get?

**Comment by nrbgt** [comment]
> Hi! Many thanks for providing inputs to the project!
It's great! Really showcases what the notebook can do with modern 
browsers. Take that, Matlab.
> I'm not too experienced in this, so I have some questions :) 
We're all learning, as has been said a few times: we're building the 
ship as we sail it. Pushing further out into other technologies is how 
we discover the boundaries, and drive future requirements.
>
> You are suggestion to use a tuple for the czml, what is the reason for 
> this, the czml language is text, there probably is a reason I dont get?
>

 From my understanding, CZML is strict JSON, and is always an array:
https://github.com/AnalyticalGraphicsInc/cesium/wiki/CZML-Structure

By changing the traitlet to a Tuple, you get all the advantages of using 
native python types, and automatic marshalling by the widget layer 
(which is already JSON-native). So, you can use the += operator to just 
push some more data onto it, make some data with generators, etc. 
without doing any json parsing/dumping.

The next step would be to do, perhaps, what bqplot does, creating a 
widget (with no DOM representation) for a Packet, and treating the 
`czml` traitlet (or just call it `packets`) as an evented list of 
subwidgets. The nice thing here would be that you could go even further 
in using native python types (like dates, etc), and for geometry things, 
using (geo)pandas or numpy for fast matrix manipulation, colour for, 
heh, color. And... hooray, there's already a JSON schema for everything 
in CZML:

https://github.com/AnalyticalGraphicsInc/czml-writer/blob/master/Schema/Packet.jsonschema

I haven't done it before, but it seems like an automated translation 
from a JSON schema to a bunch of widgets is eminently doable... and 
probably a _really_ good thing to do.

With a properly configured bunch of classes, you could build all of the 
machinery for plotting, etc. Indeed, wrapping bqplot might be a 
fantastic way to get your plotting, and give bqplot a mindblowing second 
dimension

**Comment by epifanio** [comment]
Hi @nrbgt, 

I was reworking [here](https://github.com/epifanio/CesiumWidget/blob/geojson/CesiumWidget/install.py) the way how the widget is installed and I used ```bqplot``` as a reference, nice to see you are familiar with its code. 
I was wondering if you had a chance to test the widget on [binder](), I'm having troubles in having the widget loaded (maybe the issue is how the widget get's installed) ([here](http://mybinder.org/repo/epifanio/CesiumWidget) a running instance, the example notebook get stuck at the secind cell trying to load the cesiumwidget) I'm using this [Dockerfile](https://github.com/epifanio/CesiumWidget/blob/geojson/Dockerfile). My setup.py doesn't install the static files, which are installed like in bqplot see[install_cesiumwidget.sh] (https://github.com/epifanio/CesiumWidget/blob/geojson/install_cesiumwidget.sh) used by the Dockerfile for binder.
On my fork I upgraded to latest cesium version, do you have experience on how to integrate the cesium installation using bower/npm to handle static files?

**Comment by bollwyvl** [comment]
> I was working on the way how the widget is installed and I used bqplot as a reference, code here. 

Yeah, bqplot drove a lot of the recent API enhancements to ipywidgets, so it's a good baseline.

> do you have experience on how to integrate the cesium installation using bower/npm to handle static files ?

Well, while bqplot uses bower, everything in the jupyter community is heading towards npm, which is also what cesium supports directly. I have used npm/browserify on [nbpresent](/anaconda-server/nbpresent), and it's nice.

At this point, it is unreasonable to demand an end user have node/npm/bower to _install_ a jupyter extension, so the integration should be done at build/packaging time. Then the choice becomes whether you indeed keep the dependency source in the repo, only bundle it, or some other option. I would say, with the size of cesium, it would be desirable to _not_ include it... potentially up to doing a `git filter-branch` to remove the cesium source. This is all kind of moot until the CesiumWidget is actually built as a package for pypi (and then, maybe, conda), but this isn't that big of a hurdle to overcome, it just takes a couple files.

> I was wondering if you had a chance to test the widget on binder, I'm having troubles in having the widget loaded 

Having it be an installable package would be the best way, as then it would _just work_ with a requirements.txt. But I'll take a whack at getting a binder running...

**Comment by epifanio** [comment]
Thanks @bollwyvl . 
@petrushy shall we try put the widget on pypi?
I think it is almost ready except for the "position and camera parameters streaming" so to have the zoom/fly-to functionalities working properly. Then borrow/merge the setup.py from @bollwyvl or my fork and we should ready to go.
@bollwyvl , please if you have a chance, do you mind to try the cesium widget as it is now on [binder](http://mybinder.org/repo/epifanio/CesiumWidget) ? I'm struggling in understanding why it does not load.

**Comment by bollwyvl** [comment]
> @bollwyvl , please if you have a chance, do you mind to try the cesium widget as it is now on binder ? I'm struggling in understanding why it does not load. 

Looked like you were doing a lot of work. Check out #12, based on the integration i did a few days ago for [K3D-jupyter](https://github.com/K3D-tools/K3D-jupyter).

**Comment by petrushy** [comment]
Hi, many thanks for the explanations @bollwyvl, I will learn as we go :)  Yes @epifanio, I haven't put things on pypi before but if that is of interest let us do that!

**Comment by petrushy** [comment]
The possibility of having "widgets" (that i understand sync between javascript and python) without the DOM would be interesting, I would think that especially for non-data stuff like camera, timeline, selectors, popups that could be useful.

**Comment by petrushy** [comment]
Hi! Many thanks again for the updates, I now see what you mean with the Tuple through the iss example.

I made some modifications to the setup.py script to also include the examples folder in the install. It does not install the cesium as it is now to the site-packages, which I have a feeling that maybe it should. If the nbextensions install is done from the repo directoty it seems to find the cesium, but I guess it will not be able to install it from a "setup.py install" installed version as of now.

**Comment by bollwyvl** [comment]
> The possibility of having "widgets" (that i understand sync between javascript and python) without the DOM would be interesting, I would think that especially for non-data stuff like camera, timeline, selectors, popups that could be useful. 

Well, _everything_ is data :) But being able to manipulate the camera, timeline, etc. values simply would be really cool. By going a bit beyond what the czml library does and creating them as widgets, the entire experience could be come evented and observable.

> If the nbextensions install is done from the repo directoty it seems to find the cesium, but I guess it will not be able to install it from a "setup.py install" installed version as of now.

Right, as mentioned earlier, using the `jupyter nbextension` is the high road for installing javascript to be run in the notebook. It makes it slightly harder to install, but then the user has the choice of where to put things. This is important for handling different use cases vs. the local install: jupyte hub, binder, remote kernels, etc. This difference between a python widget package and the `nbextension` is uses is not particularly well documented, but we're working on it!

**Comment by petrushy** [comment]
Ah forget my last comment, it is part of your later pull's, thanks :)

**Pull request merged**
